import os
from dotenv import load_dotenv

load_dotenv()


COINGECKO_BASE_URL = os.getenv("COINGECKO_BASE_URL")
COINGECKO_ENDPOINT = os.getenv("COINGECKO_ENDPOINT")
COINGECKO_CURRENCY = os.getenv("COINGECKO_CURRENCY", "usd")
COINGECKO_PER_PAGE = int(os.getenv("COINGECKO_PER_PAGE", 100))
COINGECKO_PAGE = int(os.getenv("COINGECKO_PAGE", 1))
COINGECKO_TIMEOUT = int(os.getenv("COINGECKO_TIMEOUT", 15))

MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT")
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY")
MINIO_SECURE = os.getenv("MINIO_SECURE", "false").lower() == "true"

BRONZE_BUCKET = os.getenv("BRONZE_BUCKET", "crypto-bronze")
SILVER_BUCKET = os.getenv("SILVER_BUCKET", "crypto-silver")

GOLD_BUCKET = os.getenv("GOLD_BUCKET", "crypto-gold")

SNOWFLAKE_USER = os.getenv("SNOWFLAKE_USER")
SNOWFLAKE_PASSWORD = os.getenv("SNOWFLAKE_PASSWORD")
SNOWFLAKE_ACCOUNT = os.getenv("SNOWFLAKE_ACCOUNT")
SNOWFLAKE_WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE")
SNOWFLAKE_DATABASE = os.getenv("SNOWFLAKE_DATABASE", "CRYPTOPULSE_DB")
SNOWFLAKE_SCHEMA = os.getenv("SNOWFLAKE_SCHEMA", "DW")
SNOWFLAKE_ROLE = os.getenv("SNOWFLAKE_ROLE")